### ISSUE TITLE
 loadVersion is not a function

### ISSUE THREAD

**Issue by anguiano** [smnhgn/vite-plugin-package-version#3]
I have this error " loadVersion is not a function" with Vite@5.0.5 when applying this change

´Add "type": "module" in the project package.json´
https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated

**Comment by smnhgn** [comment]
Hi, thanks for using the plugin.

I added a new release [(v1.1.0](https://www.npmjs.com/package/vite-plugin-package-version/v/1.1.0)) which is compatible with both cjs and esm.
